### ISSUE TITLE
apigee-istio provision on Windows fails

### ISSUE THREAD

**Issue by srinandan** [apigee/istio-mixer-adapter#178]
Looks like the proxy bundle is not created properly on Windows Please see here: https://community.apigee.com/questions/59768/apigee-with-istio.html

**Comment by theganyo** [comment]
This has been solved. Per the original poster at the link above:
"Was using git bash. From Windows command line, the apigee-istio.exe is working OK."

**Comment by vgribok** [comment]
Still having this problem with apigee-istio.exe as of adapter version 1.0.6. Ran in both regular Windows command prompt windows and GitBash - same problem, as described above. Had to get Linux version and run it in Windows Subsystem for Linux (WSL), where it did work.

**Comment by theganyo** [comment]
Would you be able to run with --verbose and post the results? (Since you've now successfully installed the proxy, you'll need to delete the istio-auth proxy, use a different org, or use the --forceProxyInstall option to get the client to attempt to install it again.)

**Comment by vgribok** [comment]
apigee-istio.exe of 1.0.6 does not appear to have "--verbose" option. It's not listed when running --help, and adding it at the end of the command line does not change the output. Using version 1.0.6 since that is Istio version installed on the GKE cluster I am working with.

**Comment by theganyo** [comment]
I was able to recreate. It appears that the proxy bundle is included in the apigee-istio.exe and is sent to the Apigee server during execution of the provisioning command, but is rejected by Apigee for some reason.
